#pragma once

#include "NativeGameplayTags.h"

namespace AIRECompanionGameplayTags
{
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AbilityCombatBasicAttack);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EventAttackRequest);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(EventAttackHit);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateAction);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateActionAttacking);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateDisabled);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateDisabledDead);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CooldownBasicAttack);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponCompanion);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponCompanionMelee);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponCompanionMeleeBasic);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DataAttackStaminaCost);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DataAttackCooldownDuration);
	AI_RE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DataDamage);
}
